/**
 * computePointColors — map each chart sample to a CSS colour string.
 *
 * Input
 * -----
 * samples  — chart dataset points: [{ x: seconds, y: mA }, …]
 * result   — return value of evaluate() from StunningEvaluationEngine:
 *              { violations, overlayHints }
 *
 * Where the data comes from
 * -------------------------
 * overlayHints.rampStart_s / rampDeadline_s / rampReachedAt_s
 *   → set by createRampHandler (ramp_to_threshold step)
 * overlayHints.completedAt_s
 *   → set by createDurationHandler / createIntegralHandler when the goal is met
 * overlayHints.glitchForgivenIntervals  [{ tStart_s, tEnd_s }]
 *   → set by createGlitchIgnoreHandler; each entry covers samples whose
 *     violation run was shorter than max_gap_ms (all-or-nothing, batch mode)
 * violations  [{ severity, tStart_s, tEnd_s, isSummary }]
 *   → generated by each step handler (sustain_thresholds, min_duration_above, …)
 *
 * Colour priority (first match wins)
 * -----------------------------------
 * blue   ramp-start marker or ramp-success marker (exact ±1 ms match)
 * gray   after goal reached, or before/during ramp phase
 * cyan   glitch-forgiven dip  [tStart_s, tEnd_s)   — strict upper bound so the
 *          clean recovery sample at tEnd_s is not painted cyan
 * red    error violation       [tStart_s, tEnd_s)   — same strict upper bound
 * yellow warn violation        [tStart_s, tEnd_s)
 * green  OK (default)
 *
 * Timestamp precision
 * -------------------
 * Chart x-coordinates are raw floats; the evaluation engine stores timestamps
 * that went through Math.round(x * 1000) / 1000 in buildLogEntry.  Rounding
 * to ms here ensures the comparisons align even when a point was dragged to a
 * sub-millisecond position.
 */
export function computePointColors(samples, result) {
  const hints  = result.overlayHints || {};
  const rampEnd = hints.rampReachedAt_s ?? hints.rampDeadline_s ?? null;

  const nonSummary = (result.violations || []).filter(v => !v.isSummary);
  const errorVios  = nonSummary.filter(v => v.severity === 'error');
  const warnVios   = nonSummary.filter(v => v.severity === 'warn');
  const forgiven   = hints.glitchForgivenIntervals || [];

  return samples.map((pt) => {
    // Round to ms to match the internal representation produced by buildLogEntry.
    const tMs = Math.round(pt.x * 1000) / 1000;

    // Blue: ramp-start marker
    if (hints.rampStart_s != null && Math.abs(tMs - hints.rampStart_s) < 0.001)
      return 'rgba(33, 150, 243, 0.9)';

    // Blue: ramp success (first sample to reach the threshold)
    if (hints.rampReachedAt_s != null && Math.abs(tMs - hints.rampReachedAt_s) < 0.001)
      return 'rgba(33, 150, 243, 0.9)';

    // Gray: after stunning goal reached
    if (hints.completedAt_s != null && tMs >= hints.completedAt_s)
      return 'rgba(160, 160, 160, 0.75)';

    // Gray: before/during ramp phase
    if (rampEnd != null && tMs <= rampEnd)
      return 'rgba(160, 160, 160, 0.75)';

    // Cyan: glitch-forgiven dip.
    // Upper bound is strict (< tEnd_s) — tEnd_s is the first clean recovery sample
    // which is genuinely OK and should be green, not cyan.
    if (forgiven.some(iv => tMs >= iv.tStart_s && tMs < iv.tEnd_s))
      return 'rgba(0, 188, 212, 0.85)';

    // Red / yellow: violation zone.
    // Same strict upper bound: tEnd_s is the first OK sample, not a violation sample.
    if (errorVios.some(v => tMs >= v.tStart_s && tMs < v.tEnd_s)) return 'rgba(220, 53, 69, 0.9)';
    if (warnVios.some(v  => tMs >= v.tStart_s && tMs < v.tEnd_s)) return 'rgba(255, 193, 7, 0.9)';

    return 'rgba(76, 175, 80, 0.9)';  // green — OK
  });
}
