/* runner.c -- C test entry point.
 * Calls every generated test function and prints a summary.
 * Generated by gen_c_tests.py; test functions are in generated_tests.c.
 */
#include "test_harness.h"
#include "generated_tests.h"

int main(void)
{
#include "runner_cases.h"
    TEST_SUMMARY();
    return 0;
}
